- hosts: localhost
  gather_facts: no

  tasks:
    - name: Add dynamic host
      add_host:
        name: "kasten-lab"
        ansible_host: "{{ ip }}"
        ansible_user: "Ubuntu admin"
        groups: dynamic_targets


- hosts: dynamic_targets
  gather_facts: no

  tasks:
    - name: Wait for SSH
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 300

    - name: Show info
      debug:
        msg: "Provisioning {{ inventory_hostname }} for {{ email }}"
