- name: Configure Cloudflared ingress rules
  hosts: kasten-lab-nas
  become: yes

  vars:
    config_path: "/mnt/Caverna_Pool_01/kasten-lab/config.yml"

    apps:
      - name: kasten
        port: 80
        protocol: http

      - name: longhorn
        port: 80
        protocol: http

      - name: homer
        port: 80
        protocol: http

      - name: restored-homer
        port: 80
        protocol: http

      - name: world
        port: 443
        protocol: https

    service_ip: "{{ ip_address }}"

  tasks:

    - name: Read existing config
      slurp:
        src: "{{ config_path }}"
      register: raw_config

    - name: Parse YAML
      set_fact:
        config: "{{ raw_config.content | b64decode | from_yaml }}"

    - name: Rewrite cloudflared config safely
      copy:
        dest: "{{ config_path }}"
        content: |
          tunnel: {{ config.tunnel }}
          credentials-file: {{ config['credentials-file'] }}

          ingress:
          {% for app in apps %}
            - hostname: {{ app.name }}-{{ labid }}.{{ domain }}
              service: {{ app.protocol }}://{{ service_ip }}:{{ app.port }}
          {% if app.name == 'world' %}
              originRequest:
                noTLSVerify: true
          {% endif %}
          {% endfor %}

            - service: http_status:404
        mode: "0775"

    - name: Restart dns container
      shell: docker restart cloudflared
