- name: Configure Cloudflared ingress rules
  hosts: kasten-lab-nas
  become: yes

  vars:
    config_path: "/mnt/Caverna_Pool_01/kasten-lab/config.yml"

    apps:
      - name: kasten
        port: 80
        protocol: http

      - name: longhorn
        port: 80
        protocol: http

      - name: homer
        port: 80
        protocol: http

      - name: world
        port: 443
        protocol: https

      - name: kstatus
        port: 31051
        protocol: http

    service_ip: "{{ ip_address }}"

  tasks:

    - name: Add ingress rules
      blockinfile:
        path: "{{ config_path }}"
        marker: "# {mark} ANSIBLE {{ item.name }}"
        insertbefore: ".*http_status:404"
        block: |
          - hostname: {{ item.name }}-{{ labid }}.{{ domain }}
            service: {{ item.protocol }}://{{ service_ip }}{% if item.port is defined and item.name == 'kstatus' %}:{{ item.port }}{% endif %}
        unsafe_writes: true
      loop: "{{ apps }}"

    - name: Restart dns container
      shell: docker restart f3de065dadf4
