- name: Install Helm 3
  hosts: kasten-lab
  become: yes

  tasks:

    - name: Log update (site)
      uri:
        url: "{{ site_webhook_logs }}"
        method: POST
        body_format: json
        body:
          lab_id: "{{ labid }}"
          message: "Instaling Helm3"
        headers:
          Content-Type: "application/json"
        validate_certs: no

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm
