- name: Install Longhorn
  hosts: all
  become: yes

  vars:
    longhornVersion: "1.9.0"

  tasks:

    - name: Add Longhorn repo
      shell: helm repo add longhorn https://charts.longhorn.io

    - name: Update Helm repos
      shell: helm repo update

    - name: Install Longhorn
      shell: >
        helm upgrade --install longhorn longhorn/longhorn
        --namespace longhorn-system
        --create-namespace
        --version "{{ longhornVersion }}"

    - name: Wait for Longhorn pods to be ready
      shell: kubectl wait --for=condition=ready pod --all -n longhorn-system --timeout=600s
