- hosts: all
  tasks:
    - debug:
        msg: "Starting full lab deploy"

# kubernetes (k3s / longhorn)
- import_playbook: ../k3s-longhorn/deploy-k3s-longhorn-single-node.yml

# veeam kasten
- import_playbook: ../kasten/deploy-kasten.yml

# minio (repo)
- import_playbook: ../minio/configure-minio-bucket.yml

# demo app
- import_playbook: ../apps/deploy-homer-app.yml
- import_playbook: ../apps/deploy-world-app.yml
