- name: Send artifact to n8n
  hosts: all
  run_once: true

  vars:
    url_webhook: "https://webhook-automation.conza.xyz/webhook/kasten-lab"
    file: "/tmp/artifact.json"

  tasks:
    - name: Read artifact
      slurp:
        src: "{{ file }}"
      register: artifact_raw

    - name: Send to n8n webhook
      uri:
        url: "{{ url_webhook }}"
        method: POST
        body_format: json
        body: "{{ artifact_raw.content | b64decode | from_json }}"
        headers:
          Content-Type: "application/json"
