- name: Deploy Homer App
  hosts: kasten-lab
  become: yes

  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    homerdemo_host: "homer-{{ labid }}.{{ domain }}"
    use_artifact: "{{ use_artifact | default(false) }}"

  tasks:

    - name: Apply Homer persistent resources
      shell: >
        kubectl apply -f https://raw.githubusercontent.com/ricardoconzatti/demo/refs/heads/main/homer-demo/Kubernetes/homer-demo-persistent.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Apply Homer ingress
      shell: >
        kubectl apply -f https://raw.githubusercontent.com/ricardoconzatti/demo/refs/heads/main/homer-demo/Kubernetes/homer-demo-ingress.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Patch ingress hostname
      shell: >
        kubectl patch ingress homer-demo-ingress -n homer-demo
        --type merge
        -p '{"spec":{"rules":[{"host":"{{ homerdemo_host }}","http":{"paths":[{"path":"/","pathType":"Prefix","backend":{"service":{"name":"homer-web","port":{"number":80}}}}]}}]}}'
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Print URL
      debug:
        msg: "Homer demo app URL: https://{{ homerdemo_host }}"

    - name: Log update (site)
      uri:
        url: "{{ site_webhook_logs }}"
        method: POST
        body_format: json
        body:
          lab_id: "{{ labid }}"
          message: "Homer demo deployed"
          detail: "https://{{ homerdemo_host }}"
        headers:
          Content-Type: "application/json"
        validate_certs: no

    - name: Add demo app (homer) to artifact
      include_role:
        name: artifact
      vars:
        artifact_section:
          demo_apps:
            homer:
              url: "https://{{ homerdemo_host }}"
      when: use_artifact
