- name: Deploy Homer App
  hosts: all
  become: yes

  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml

  tasks:

    - name: Apply Homer persistent resources
      shell: kubectl apply -f https://raw.githubusercontent.com/ricardoconzatti/demo/refs/heads/main/homer-demo/Kubernetes/homer-demo-persistent.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Apply Homer ingress
      shell: kubectl apply -f https://raw.githubusercontent.com/ricardoconzatti/demo/refs/heads/main/homer-demo/Kubernetes/homer-demo-ingress.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
