- name: Deploy Homer App
  hosts: all
  become: yes

  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    homerdemo_host: "homer-{{ inventory_hostname.split('.')[-1] }}.caverna.local"

  tasks:

    - name: Apply Homer persistent resources
      shell: kubectl apply -f https://raw.githubusercontent.com/ricardoconzatti/demo/refs/heads/main/homer-demo/Kubernetes/homer-demo-persistent.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Apply Homer ingress
      shell: kubectl apply -f https://raw.githubusercontent.com/ricardoconzatti/demo/refs/heads/main/homer-demo/Kubernetes/homer-demo-ingress.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig }}"


- name: Patch Ingress hostname
  hosts: localhost
  gather_facts: false

  vars:
    homerdemo_host: "homer-{{ inventory_hostname.split('.')[-1] }}.caverna.local"

  tasks:

    - name: Patch ingress host
      kubernetes.core.k8s:
        state: patched
        kind: Ingress
        namespace: homer-demo
        name: homer-demo-ingress
        definition:
          spec:
            rules:
              - host: "{{ homerdemo_host }}"


- name: Show URL
  hosts: localhost
  gather_facts: false

  vars:
    homerdemo_host: "homer-{{ inventory_hostname.split('.')[-1] }}.caverna.local"

  tasks:

    - name: Print URL
      debug:
        msg: "Homer demo URL: http://{{ homerdemo_host }}"
