- name: Configure Kasten Ingress (HTTPS)
  hosts: all
  become: yes

  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    domain: "caverna.local"
    kasten_host: "kasten-{{ inventory_hostname.split('.')[-1] }}.{{ domain }}"
    tls_secret: "kasten-{{ inventory_hostname.split('.')[-1] }}-tls"

  tasks:

    - name: Create Kasten Ingress (HTTPS)
      shell: |
        cat <<EOF | kubectl apply -f -
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: kasten-traefik-ingress
          namespace: kasten-io
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
        spec:
          ingressClassName: traefik
          tls:
          - hosts:
            - {{ kasten_host }}
            secretName: {{ tls_secret }}
          rules:
          - host: {{ kasten_host }}
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: gateway
                    port:
                      number: 80
        EOF
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Show Kasten URL
      debug:
        msg: "Kasten URL: https://{{ kasten_host }}/k10/#"

    - name: Add Kasten (ingress) to artifact
      include_role:
        name: artifact
      vars:
        artifact_section:
          kasten:
            url: "https://{{ kasten_host }}/k10/#"

