- name: Create Kasten ServiceAccount and Token
  hosts: all
  become: yes

  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    sa_name: svc-kasten-local
    namespace: kasten-io
    role_name: svc-kasten-local-admin

  tasks:

    - name: Create ServiceAccount
      shell: kubectl -n {{ namespace }} create serviceaccount {{ sa_name }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      ignore_errors: true

    - name: Create ClusterRoleBinding
      shell: >
        kubectl create clusterrolebinding {{ role_name }}
        --clusterrole=cluster-admin
        --serviceaccount={{ namespace }}:{{ sa_name }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      ignore_errors: true

    - name: Generate token (long duration)
      shell: >
        kubectl -n {{ namespace }} create token {{ sa_name }} --duration=8760h
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: token_output

    - name: Show credentials
      debug:
        msg:
          - "User: {{ sa_name }}"
          - "Role: cluster-admin"
          - "Token: {{ token_output.stdout }}"
