- hosts: kasten-lab
  gather_facts: no
  vars:
    use_artifact: true

  tasks:
    - name: Register start time
      set_fact:
        lab_start_time: "{{ lookup('pipe', 'date +%s') | int }}"
      run_once: true

    - name: Starting message
      debug:
        msg: "##### Starting full Kasten lab deploy"
      run_once: true

    - name: Ensure lab directory exists
      file:
        path: "{{ labdir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

# IMPORT PLAYBOOKS

# k3s
- import_playbook: ../k3s/deploy-k3s-single-node.yml

# longhorn
- import_playbook: ../longhorn/deploy-longhorn-single-node.yml

# veeam kasten
- import_playbook: ../kasten/deploy-kasten.yml

# minio (repo)
- import_playbook: ../minio/configure-minio-bucket.yml

# demo app
- import_playbook: ../apps/deploy-homer-app.yml
- import_playbook: ../apps/deploy-world-app.yml

# CALCULATE TIME + ARTIFACT

- hosts: all
  gather_facts: no

  tasks:
    - name: Register end time
      set_fact:
        lab_end_time: "{{ lookup('pipe', 'date +%s') | int }}"
      run_once: true

    - name: Calculate total duration
      set_fact:
        lab_duration_seconds: "{{ (lab_end_time | int) - (lab_start_time | int) }}"
      run_once: true

    - name: Calculate duration parts
      set_fact:
        duration_min: "{{ (lab_duration_seconds | int) // 60 }}"
        duration_sec: "{{ (lab_duration_seconds | int) % 60 }}"
      run_once: true

    - name: Format duration
      set_fact:
        lab_duration_pretty: >-
          {{
            duration_min ~ ' minute' ~
            ( 's' if duration_min != 1 else '' )
            ~ ' and ' ~
            duration_sec ~ ' second' ~
            ( 's' if duration_sec != 1 else '' )
          }}
      run_once: true

    - name: Show duration
      debug:
        msg: "Total lab deploy time: {{ lab_duration_pretty }}"
      run_once: true

    - name: Add duration to artifact
      include_role:
        name: artifact
      vars:
        artifact_section:
          lab:
            id: "{{ labid }}"
            duration_seconds: "{{ lab_duration_seconds }}"
            duration_pretty: "{{ lab_duration_pretty }}"
      when: use_artifact | default(false)
      run_once: true

# SEND TO N8N
- import_playbook: send-files-n8n.yml
