- hosts: kasten-lab
  gather_facts: no

  tasks:

    - name: Cleanup message
      debug:
        msg: "##### Cleaning up Kasten lab {{ labid }}"
      run_once: true
      
# IMPORT PLAYBOOKS

# minio
- import_playbook: remove-minio-bucket.yml

# vmware vm
- import_playbook: remove-lab-vm.yml
