- name: Remove Lab VM (n8n)
  hosts: kasten-lab
  run_once: true

  tasks:

    - name: Send to n8n webhook
      uri:
        url: "{{ n8n_webhook_remove }}"
        method: POST
        body_format: json
        body:
          labid: "{{ labid }}"
        headers:
          Content-Type: "application/json"
